from ..zadanie_obowiazkowe import *
from ..przypisania import *
from ..przypisania_z_wieloma_celami_i_wspoldzielone_referencje import *
from ..przypisania_rozszerzone_i_wspoldzielone_referencje import *
from ..techniki_tworzenia_petli_uzupelnienie import *
from ..iteratory_dokumentowanie_kodu_funkcje_argumenty import *
from ..zasiegi import *
from ..adnotacje import *
from ..funkcje_anonimowe import *
from ..generatory import *
